### ISSUE TITLE
The configuration in config.yaml is not being read.

### ISSUE THREAD

**Issue by zexry619** [moeakwak/chatgpt-web-share#176]
**Version**
v0.x.x

**What's your deploying environment?**
- [ ] Docker

This project is very helpful and excellent, but I encountered an issue where I’ve already created my config file in the same directory as the docker-compose.yaml file, but the config file is not being read when I run it with docker compose up -d.

It reads the template file, and I have set the passwords in the config.yaml file for both the administrator and user. However, after opening the web interface, the passwords I set in the config.yaml file don’t work. When I try using the default password, which is adminadmin, it works fine.

Can you help me solve this problem?

Is there something wrong with my deployment process?

**Comment by moeakwak** [comment]
Hi, it looks like you may have incorrect paths set in your docker-compose.yaml file. Please provide the content of your docker-compose.yaml file.

**Comment by zexry619** [comment]
I have already placed it in one path with my docker-compose.yml, which is /root/cws. However, it still cannot be read.

I am using what you shared in your English documentation.

Here is my docker-compose file:
```
version: "3"

services:
  chatgpt-share:
    image: ghcr.io/moeakwak/chatgpt-web-share:latest
    container_name: chatgpt-web-share
    restart: always
    network_mode: bridge
    ports:
      - 8083:80 # web port
      # - 6060:6060 # optional: this is the port for ChatGPT-Proxy-V4 reverse proxy, you can expose it for other services
    volumes:
      - ./data:/data # store database files and statistics data
      - ./config.yaml:/app/backend/api/config/config.yaml # backend configuration file
      - ./logs:/app/logs # store log files
 ```
 
 and config.yaml same with your docs.

Is there anything else I need to fix?


Thank you.

**Comment by moeakwak** [comment]
It seems like there is no issue with your docker-compose.yaml file.

> It reads the template file, and I have set the passwords in the config.yaml file for both the administrator and user. However, after opening the web interface, the passwords I set in the config.yaml file don’t work. When I try using the default password, which is adminadmin, it works fine.

Please note that once the admin user is created, changing the password in the config.yaml file will not have any effect. To change the password, you should go to the web interface to reset the password (settings icon).

And, if other configurations in your config.yaml have no effect, it’s possible that there is a problem with that specific file.

**Comment by zexry619** [comment]
This is my config.yaml file:
```
print_sql: false
host: "127.0.0.1"
port: 8000
data_dir: /data # <------ added in v0.3.0
database_url: "sqlite+aiosqlite:////data/database.db" # Note: there are four slashes here, indicating that the file is located in the /data directory and using an absolute path.
run_migration: false # whether to run database migration at startup, currently unnecessary

jwt_secret: "********" # used for generating jwt token, fill in a random string
jwt_lifetime_seconds: 86400 # jwt token expiration time
cookie_max_age: 86400 # cookie expiration time
user_secret: "********" # used for generating user passwords, fill in a random string

sync_conversations_on_startup: true # whether to synchronize conversations in ChatGPT on startup, recommended. When enabled, it will automatically synchronize newly added conversations in ChatGPT to the database and mark conversations no longer in ChatGPT as invalid.
create_initial_admin_user: true # whether to create an initial administrator user
initial_admin_username: admin # initial administrator username
initial_admin_password: admin # initial administrator password
ask_timeout: 600    # used to limit the maximum time of a conversation

chatgpt_access_token: "********" # needs to be obtained from ChatGPT, see below
chatgpt_paid: false # whether it is a ChatGPT Plus user

# Note! If you are a plus user, please uncomment the following and fill in reverse_proxy_puid as explained later in the document.
# chatgpt_base_url: http://127.0.0.1:6060/api/
# run_reverse_proxy: true
# reverse_proxy_port: 6060
# reverse_proxy_binary_path: /app/backend/ChatGPT-Proxy-V4
# reverse_proxy_puid: "_puid value from cookie"
# auto_refresh_reverse_proxy_puid: true # whether to update puid automatically

log_dir: /app/logs # log storage location, do not modify casually
console_log_level: INFO # log level, set to DEBUG to obtain more information

# Note: the following are added in v0.3.0 for statistics
request_log_counter_time_window: 2592000 # request log time range, default is the last 30 days
request_log_counter_interval: 1800 # request log statistics granularity, default is 30 minutes
ask_log_time_window: 2592000 # conversation log time range, default is the last 7 days
sync_conversations_regularly: yes # whether sync conversations from chatgpt account every 12 hours
```

Is there something wrong? Then what if I want to rebuild everything with a new password and user?

**Comment by zexry619** [comment]
and please update your english manual documentation.

**Comment by moeakwak** [comment]
1. Your config seems have no problem. If your config.yaml is functioning correctly, then the issue may not be related to the volume configuration in your docker-compose.yaml file.
2. If you wish to reset the entire system, you can simply delete the database file. This will remove all the existing data and allow you to start fresh.
3. The English documentation will be updated after the release of version 0.4.0, as it includes significant changes.

**Comment by LuneZ99** [comment]
The config.yaml file given in [中文指南](https://github.com/moeakwak/chatgpt-web-share/wiki/%E4%B8%AD%E6%96%87%E6%8C%87%E5%8D%97) and [English Guide](https://github.com/moeakwak/chatgpt-web-share/blob/dev/README.en.md) now is indeed not work properly. After debugging in the development environment, I found that almost all of the config changes would not work since Config is defined as shown below and did not fit into config.yaml.
```python
@singleton_with_lock
class Config(BaseConfig[ConfigModel]):
    if _TYPE_CHECKING:
        common: CommonSetting = CommonSetting()
        http: HttpSetting = HttpSetting()
        data: DataSetting = DataSetting()
        auth: AuthSetting = AuthSetting()
        revchatgpt: RevChatGPTSetting = RevChatGPTSetting()
        api: APISetting = APISetting()
        log: LogSetting = LogSetting()
        stats: StatsSetting = StatsSetting()

    def __init__(self):
        super().__init__(ConfigModel, "config.yaml")
```

By adjusting the config.yaml to the following format without modifying the project code, all the configurations were loaded properly. All the dictionary structures need to match the class definitions.

```yaml
data:
  data_dir: /path/to/your/data # <------ v0.3.0 以上新增
  database_url: "sqlite+aiosqlite:////path/to/your/database.db" # 特别注意：这里有四个斜杠，代表着文件位于 /data 目录，使用的是绝对路径
  mongodb_url: "mongodb://mongo-server-ip:27017"
  run_migration: false # 是否在启动时运行数据库迁移，目前没有必要启用

http:
  host: "127.0.0.1"
  port: 8000

auth:
  jwt_secret: "12345678" # 用于生成 jwt token，自行填写随机字符串
  jwt_lifetime_seconds: 86400 # jwt token 过期时间
  cookie_max_age: 86400 # cookie 过期时间
  user_secret: "12345678" # 用于生成用户密码，自行填写随机字符串

common:
  sync_conversations_regularly: true # 是否定期（每隔12小时）从账号中同步一次对话
  sync_conversations_on_startup: true # 是否在启动时同步同步 ChatGPT 对话，建议启用。启用后，将会自动将 ChatGPT 中新增的对话同步到数据库中，并把已经不在 ChatGPT 中的对话标记为无效
  create_initial_admin_user: true # 是否创建初始管理员用户
  initial_admin_user_username: cws # 初始管理员用户名
  initial_admin_user_password: cwspassword # 初始管理员密码
  ask_timeout: 600    # 用于限制对话的最长时间
  print_sql: false

#chatgpt_access_token: "你的access_token" # 需要从 ChatGPT 获取，见后文
#chatgpt_paid: true # 是否为 ChatGPT Plus 用户

# 注意：如果你希望使用公共代理，或使用整合的 go-proxy-api，请保持注释；如果需要自定义，注意最后一定要有一个斜杠
# 在实际请求时，chatgpt_base_url 优先级为：config 内定义 > 环境变量 > revChatGPT 内置的公共代理
chatgpt_base_url: http://127.0.0.1:8080/

log:
  log_dir: /app/logs # 日志存储位置，不要随意修改
  console_log_level: DEBUG # 日志等级，设置为 DEBUG 能够获得更多信息

# 以下用于统计，如不清楚可保持默认
request_log_counter_time_window: 2592000 # 请求日志时间范围，默认为最近 30 天
request_log_counter_interval: 1800 # 请求日志统计粒度，默认为 30 分钟
ask_log_time_window: 2592000 # 对话日志时间范围，默认为最近 7 天

```
