### ISSUE TITLE
分享我的docker-compose（v0.4.0-alpha2版本）

### ISSUE THREAD

**Issue by wangjueszu** [moeakwak/chatgpt-web-share#187]
使用环境：

1. 美国服务器（可直连openai、固定IP）
2. docker版本/Docker version 23.0.5, build bc4487a
3. docker-compose版本/Docker version 23.0.5, build bc4487a

搭建方法：

1. 创建一个文件夹，如/www/wwwroot/cws
2. 文件夹下创建一个文件，“docker-compose.yml”，其中填充内容如下：

```version: "3"

services:
  chatgpt-web-share:
    image: ghcr.io/moeakwak/chatgpt-web-share:0.4.0-alpha2
    container_name: cws
    restart: always
    ports:
      - 8092:80  #端口可调整
    volumes:
      - ./data:/app/backend/data
    environment:
      - TZ=Asia/Shanghai
      - CWS_CONFIG_DIR=/app/backend/data/config
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/
    depends_on:
      - mongo
      - go-chatgpt-api

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: cws
      MONGO_INITDB_ROOT_USERNAME: cws
      MONGO_INITDB_ROOT_PASSWORD: password


  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api:latest
    environment:
      - GIN_MODE=release
    restart: unless-stopped
```

3. 在刚刚创建的文件夹中再创建一个文件夹data（如/www/wwwroot/cws/data）
4. 在data中创造两个文件夹config和logs（如/www/wwwroot/cws/data/config 和如/www/wwwroot/cws/data/logs)
5. config中创建两个文件“config.yaml”和“credentials.yaml”

6. “config.yaml”内容如下
```
common:
  print_sql: false
  create_initial_admin_user: true
  initial_admin_user_username: admin
  initial_admin_user_password: password
  sync_conversations_on_startup: true
  sync_conversations_regularly: false
http:
  host: 127.0.0.1
  port: 8000
  cors_allow_origins:
  - http://localhost
  - http://127.0.0.1
data:
  data_dir: ./data
  database_url: sqlite+aiosqlite:///data/database.db
  mongodb_url: mongodb://cws:password@mongo:27017
  run_migration: false
auth:
  jwt_secret: MODIFY_THIS_TO_RANDOM_SECRET
  jwt_lifetime_seconds: 86400
  cookie_max_age: 86400
  cookie_name: user_auth
  user_secret: MODIFY_THIS_TO_RANDOM_SECRET
revchatgpt:
  is_plus_account: false
#  chatgpt_base_url:
  ask_timeout: 600
api:
  openai_base_url: https://api.openai.com/v1/
  connect_timeout: 10
  read_timeout: 10
log:
  console_log_level: INFO
stats:
  request_counter_time_window: 2592000
  request_counts_interval: 1800
  ask_log_time_window: 604800
```
7. “credentials.yaml”内容如下
```
chatgpt_access_token: "ey***cg"
openai_api_key: "sk-f****w"
```
8. 返回文件夹如/www/wwwroot/cws，执行命令docker-compose up -d 即可。

如果帮助到你了，点个赞吧

**Comment by wangjueszu** [comment]
如果你需要在一个服务器中建立多个“chatgpt-web-share”，可以新建一个文件夹，重复上面的操作，但修改如下内容：

1. “docker-compose.yml”
```

services:
  chatgpt-web-share:
    image: ghcr.io/moeakwak/chatgpt-web-share:0.4.0-alpha2
    container_name: cws
    restart: always
    ports:
      - 8093:80  #更改一个和前面不一样的端口号
    volumes:
      - ./data:/app/backend/data
    environment:
      - TZ=Asia/Shanghai
      - CWS_CONFIG_DIR=/app/backend/data/config
      - CHATGPT_BASE_URL=http://go-chatgpt-api-1:8080/chatgpt/ #添加‘-1’做代理区分
    depends_on:
      - mongo
      - go-chatgpt-api-1#添加‘-1’做代理区分

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: cws
      MONGO_INITDB_ROOT_USERNAME: cws
      MONGO_INITDB_ROOT_PASSWORD: password


  go-chatgpt-api-1:     #添加‘-1’做代理区分
    container_name: go-chatgpt-api-1  #添加‘-1’做代理区分
    image: linweiyuan/go-chatgpt-api:latest
    environment:
      - GIN_MODE=release
    restart: unless-stopped
```
2. “credentials.yaml”
```
chatgpt_access_token: "ey***sd"  #换另外一个GPT账户的
openai_api_key: "sk-f****w"
```

**Comment by h3m4** [comment]
感谢，跟着这个已经搞出来了

**Comment by Chris930101** [comment]
这个没看到填域名的地方。
当然，我在0.3.15版本填了域名的，通用的吗

**Comment by wangjueszu** [comment]
> 这个没看到填域名的地方。
> 当然，我在0.3.15版本填了域名的，通用的吗

域名应该指的是有其他代理的方式，由于本服务器可以直连openai故删除了。

**Comment by robbit69** [comment]
非常感谢佬哥，但是有一个问题想请教。

现在容器已经跑起来了，并且可以使用api进行回答，但是使用chatgpt账号会出现null，我不确定chatgpt base url应该写什么，直接写 http://go-chatgpt-api:{自定端口号}/chatgpt/ 后问题依旧了，又折腾了一下结果API也不能用了

**Comment by sbilly** [comment]
美国 vps 被拉黑了，增加了个 `chatgpt-proxy-server-warp` 跑起来了

```yaml
services:
  chatgpt-web-share:
    image: ghcr.io/moeakwak/chatgpt-web-share:0.4.0-alpha2
    container_name: cws
    restart: always
    ports:
      - 172.17.0.1:8092:80  #端口可调整
    volumes:
      - /opt/disk2/data/chatgpt-web-share/data:/app/backend/data
    environment:
      - TZ=Asia/Shanghai
      - CWS_CONFIG_DIR=/app/backend/data/config
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/
    depends_on:
      - mongo
      - go-chatgpt-api

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - /opt/disk2/data/chatgpt-web-share/mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: cws
      MONGO_INITDB_ROOT_USERNAME: cws
      MONGO_INITDB_ROOT_PASSWORD: password


  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api:latest
    environment:
      - GIN_MODE=release
      - GO_CHATGPT_API_PROXY=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server-warp
    restart: unless-stopped


  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    environment:
      - LOG_LEVEL=OFF
    restart: unless-stopped
```

**Comment by Chris930101** [comment]
> 
我的服务器也是能直连的，添加域名是为了国内直连吧

**Comment by Chris930101** [comment]
> > 这个没看到填域名的地方。
> > 当然，我在0.3.15版本填了域名的，通用的吗
> 
> 域名应该指的是有其他代理的方式，由于本服务器可以直连openai故删除了。

我想起来了，添加域名是为了caddy, 有位大佬把caddy整合到了docker-compose.yml里，我按照那个操作虽然没成功，后面gpt帮我改了一个版本出来：
version: "3"

services:
  chatgpt-share:
    image: ghcr.io/moeakwak/chatgpt-web-share:latest
    restart: always
    expose:
      - 80
    volumes:
      - ./data:/data
      - ./config.yaml:/app/backend/api/config/config.yaml
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/
    depends_on:
      - go-chatgpt-api
    labels:
      caddy: 填写域名
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - caddy

  go-chatgpt-api:
    image: linweiyuan/go-chatgpt-api
    expose:
      - 8080
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped
    networks:
      - caddy

  chatgpt-proxy-server:
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped
    networks:
      - caddy

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data:
    driver: local
    driver_opts:
      type: none
      device: /cws/caddy_proxy
      o: bind

**Comment by wangjueszu** [comment]
> 非常感谢佬哥，但是有一个问题想请教。
> 
> 现在容器已经跑起来了，并且可以使用api进行回答，但是使用chatgpt账号会出现null，我不确定chatgpt base url应该写什么，直接写 [http://go-chatgpt-api:{自定端口号}/chatgpt/](http://go-chatgpt-api:%7B%E8%87%AA%E5%AE%9A%E7%AB%AF%E5%8F%A3%E5%8F%B7%7D/chatgpt/) 后问题依旧了，又折腾了一下结果API也不能用了

参考“美国 vps 被拉黑了，增加了个 chatgpt-proxy-server-warp 跑起来了”这位哥们的试下，可能你的服务器并不能直接访问openai。

**Comment by wangjueszu** [comment]
> > > 这个没看到填域名的地方。
> > > 当然，我在0.3.15版本填了域名的，通用的吗
> > 
> > 域名应该指的是有其他代理的方式，由于本服务器可以直连openai故删除了。
> 
> 我想起来了，添加域名是为了caddy, 有位大佬把caddy整合到了docker-compose.yml里，我按照那个操作虽然没成功，后面gpt帮我改了一个版本出来：
> version: "3"
> 
> services:
>   chatgpt-share:
>     image: ghcr.io/moeakwak/chatgpt-web-share:latest
>     restart: always
>     expose:
>       - 80
>     volumes:
>       - ./data:/data
>       - ./config.yaml:/app/backend/api/config/config.yaml
>       - ./logs:/app/logs
>     environment:
>       - TZ=Asia/Shanghai
>       - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/
>     depends_on:
>       - go-chatgpt-api
>     labels:
>       caddy: 填写域名
>       caddy.reverse_proxy: "{{upstreams 80}}"
>     networks:
>       - caddy
> 
>   go-chatgpt-api:
>     image: linweiyuan/go-chatgpt-api
>     expose:
>       - 8080
>     environment:
>       - GIN_MODE=release
>       - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
>     depends_on:
>       - chatgpt-proxy-server
>     restart: unless-stopped
>     networks:
>       - caddy
> 
>   chatgpt-proxy-server:
>     image: linweiyuan/chatgpt-proxy-server
>     restart: unless-stopped
>     networks:
>       - caddy
> 
>   caddy:
>     image: lucaslorentz/caddy-docker-proxy:ci-alpine
>     ports:
>       - 80:80
>       - 443:443
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
>       - caddy_data:/data
>     environment:
>       - CADDY_INGRESS_NETWORKS=caddy
>     networks:
>       - caddy
>     restart: unless-stopped
> 
> networks:
>   caddy:
>     external: true
> 
> volumes:
>   caddy_data:
>     driver: local
>     driver_opts:
>       type: none
>       device: /cws/caddy_proxy
>       o: bind
> 

可以的话，提供下你的文件目录。
这种方式，是不是部署完就支持https访问了。对nginx的安装位置有要求否。

**Comment by robbit69** [comment]
> > 非常感谢佬哥，但是有一个问题想请教。
> > 现在容器已经跑起来了，并且可以使用api进行回答，但是使用chatgpt账号会出现null，我不确定chatgpt base url应该写什么，直接写 [http://go-chatgpt-api:{自定端口号}/chatgpt/](http://go-chatgpt-api:%7B%E8%87%AA%E5%AE%9A%E7%AB%AF%E5%8F%A3%E5%8F%B7%7D/chatgpt/) 后问题依旧了，又折腾了一下结果API也不能用了
> 
> 参考“美国 vps 被拉黑了，增加了个 chatgpt-proxy-server-warp 跑起来了”这位哥们的试下，可能你的服务器并不能直接访问openai。

好的老哥

**Comment by Chris930101** [comment]
> 可以的话，提供下你的文件目录。 这种方式，是不是部署完就支持https访问了。对nginx的安装位置有要求否。

是的，我是https访问的，我是caddy，不是nginx，我是创建了一个文件 用来存放caddy数据的，其他的好像没改动啥。
以下是cws下的文件：
![044cfc8a4f25ca5c775e4e9f774d4fd](https://github.com/moeakwak/chatgpt-web-share/assets/37211344/c91f0f28-e4e4-456a-8dd1-4d324822f9d5)

**Comment by dankey** [comment]
请教一下，跑起来了，登录页面能看到。账号密码在哪设置？
输入用户名密码，提示 Request Error。

**Comment by itgoyo** [comment]
> 使用环境：
> 
> 1. 美国服务器（可直连 openai、固定 IP）
> 2. docker 版本 / Docker version 23.0.5, build bc4487a
> 3. docker-compose 版本 / Docker version 23.0.5, build bc4487a
> 
> 搭建方法：
> 
> 1. 创建一个文件夹，如 /www/wwwroot/cws
> 2. 文件夹下创建一个文件，“docker-compose.yml”，其中填充内容如下：
> 
> ```
> 
> services:
>   chatgpt-web-share:
>     image: ghcr.io/moeakwak/chatgpt-web-share:0.4.0-alpha2
>     container_name: cws
>     restart: always
>     ports:
>       - 8092:80  #端口可调整
>     volumes:
>       - ./data:/app/backend/data
>     environment:
>       - TZ=Asia/Shanghai
>       - CWS_CONFIG_DIR=/app/backend/data/config
>       - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/
>     depends_on:
>       - mongo
>       - go-chatgpt-api
> 
>   mongo:
>     image: mongo:6.0
>     restart: always
>     volumes:
>       - ./mongo_data:/data/db
>     environment:
>       MONGO_INITDB_DATABASE: cws
>       MONGO_INITDB_ROOT_USERNAME: cws
>       MONGO_INITDB_ROOT_PASSWORD: password
> 
> 
>   go-chatgpt-api:
>     container_name: go-chatgpt-api
>     image: linweiyuan/go-chatgpt-api:latest
>     environment:
>       - GIN_MODE=release
>     restart: unless-stopped
> ```
> 
> 3. 在刚刚创建的文件夹中再创建一个文件夹 data（如 /www/wwwroot/cws/data）
> 4. 在 data 中创造两个文件夹 config 和 logs（如 /www/wwwroot/cws/data/config 和如 /www/wwwroot/cws/data/logs)
> 5. config 中创建两个文件 “config.yaml” 和 “credentials.yaml”
> 6. “config.yaml” 内容如下
> 
> ```
> common:
>   print_sql: false
>   create_initial_admin_user: true
>   initial_admin_user_username: admin
>   initial_admin_user_password: password
>   sync_conversations_on_startup: true
>   sync_conversations_regularly: false
> http:
>   host: 127.0.0.1
>   port: 8000
>   cors_allow_origins:
>   - http://localhost
>   - http://127.0.0.1
> data:
>   data_dir: ./data
>   database_url: sqlite+aiosqlite:///data/database.db
>   mongodb_url: mongodb://cws:password@mongo:27017
>   run_migration: false
> auth:
>   jwt_secret: MODIFY_THIS_TO_RANDOM_SECRET
>   jwt_lifetime_seconds: 86400
>   cookie_max_age: 86400
>   cookie_name: user_auth
>   user_secret: MODIFY_THIS_TO_RANDOM_SECRET
> revchatgpt:
>   is_plus_account: false
> #  chatgpt_base_url:
>   ask_timeout: 600
> api:
>   openai_base_url: https://api.openai.com/v1/
>   connect_timeout: 10
>   read_timeout: 10
> log:
>   console_log_level: INFO
> stats:
>   request_counter_time_window: 2592000
>   request_counts_interval: 1800
>   ask_log_time_window: 604800
> ```
> 
> 7. “credentials.yaml” 内容如下
> 
> ```
> chatgpt_access_token: "ey***cg"
> openai_api_key: "sk-f****w"
> ```
> 
> 8. 返回文件夹如 /www/wwwroot/cws，执行命令 docker-compose up -d 即可。
> 
> 如果帮助到你了，点个赞吧

兄弟，按照你的方法搭建，前两天开始报错了，请问这个有什么解决思路么？

![image](https://github.com/moeakwak/chatgpt-web-share/assets/23348551/607895cb-cf24-44ee-99af-5e30348bec5f)

**Comment by Lodour** [comment]
[go-chatgpt-url](https://github.com/linweiyuan/go-chatgpt-api) 又改了 API

上面的配置文件需要把 `CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/` 改成 `CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/backend-api/`

**Comment by h1xy** [comment]
一台VPS部署多个CWS应该可以共享一个go-chatgpt-api， 不需要起多个docker，就是CHATGPT_BASE_URL要注意下，见[作者中文部署文档](https://github.com/moeakwak/chatgpt-web-share/wiki/%E4%B8%AD%E6%96%87%E6%8C%87%E5%8D%97#%E5%88%86%E7%A6%BB%E9%83%A8%E7%BD%B2-go-chatgpt-api)。

**Comment by cmlibo** [comment]
你们的配置文档哪里来的

**Comment by tchivs** [comment]
更新alpha4.4 版本
docker-compose里面的Image改成alpha4.4：

> image: ghcr.io/moeakwak/chatgpt-web-share:0.4.0-alpha4.4

修改config.yaml配置如下

```yaml
openai_web:
  is_plus_account: false
  chatgpt_base_url: http://go-chatgpt-api:8080/chatgpt/backend-api/
  proxy:
  common_timeout: 10
  ask_timeout: 600
openai_api:
  openai_base_url: https://api.openai.com/v1/
  proxy:
  connect_timeout: 10
  read_timeout: 20
common:
  print_sql: false
  create_initial_admin_user: true
  initial_admin_user_username: admin
  initial_admin_user_password: password
  sync_conversations_on_startup: true
  sync_conversations_regularly: false
http:
  host: 127.0.0.1
  port: 8000
  cors_allow_origins:
  - http://localhost
  - http://127.0.0.1
data:
  data_dir: ./data
  database_url: sqlite+aiosqlite:///data/database.db
  mongodb_url: mongodb://cws:password@mongo:27017
  run_migration: false
auth:
  jwt_secret: MODIFY_THIS_TO_RANDOM_SECRET
  jwt_lifetime_seconds: 86400
  cookie_max_age: 86400
  cookie_name: user_auth
  user_secret: MODIFY_THIS_TO_RANDOM_SECRET
stats:
  ask_stats_ttl: 7776000
  request_stats_ttl: 2592000
  request_stats_filter_keywords:
  - /status
log:
  console_log_level: INFO

```
