### ISSUE TITLE
docker 内时区不对

### ISSUE THREAD

**Issue by xixi-furry** [moeakwak/chatgpt-web-share#213]
**Version**
v0.4.0-alpha4.3

**What's your deploying environment?**

- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
在容器内使用```date +"%Z %z"```提示为CST+0800 但是在后台里查看所有的时间都是+000，感觉时区获取的有问题，包括mongo的变量都加了使用中国时区

**Expected behavior**

**Your config.yaml or other configurations**
docker-compose文件：
```yaml
version: "3"

services:
  chatgpt-share:
    image: ghcr.io/moeakwak/chatgpt-web-share:0.4.0-alpha4.3
    restart: always
    ports:
      - 8080:80 # web 端口号
    volumes:
      - ./data:/app/backend/data # 存放数据库文件以及统计数据
      - ./Caddyfile:/app/Caddyfile
    environment:
      - TZ=Asia/Shanghai
      - CWS_CONFIG_DIR=/app/backend/data/config
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/backend-api/
    depends_on:
      - mongo
      - go-chatgpt-api

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: cws
      MONGO_INITDB_ROOT_USERNAME: cws
      MONGO_INITDB_ROOT_PASSWORD: password
      TZ: Asia/Shanghai

  go-chatgpt-api:
    image: linweiyuan/go-chatgpt-api:latest
#    ports:
#      - 6060:8080 # 如果你需要暴露端口如一带多，可以取消注释
    environment:
      - GIN_MODE=release
      - GO_CHATGPT_API_ARKOSE_TOKEN_URL=https://arkose-token.linweiyuan.com
#      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
#      - NETWORK_PROXY_SERVER=http://host:port
    restart: unless-stopped

```

**Screenshots or running logs**
![image](https://github.com/moeakwak/chatgpt-web-share/assets/59167815/31129d71-718e-442b-b87a-f783e47bc004)
![image](https://github.com/moeakwak/chatgpt-web-share/assets/59167815/d5c82d1f-1dd2-49bd-840e-ebcbd5c049a9)

日志正常：
![image](https://github.com/moeakwak/chatgpt-web-share/assets/59167815/9a61c520-8887-4e30-bbd5-714e375fc8aa)

**Additional context**
