### ISSUE TITLE
api.exceptions.ConfigException: ConfigException: [-1] errors.config Config file not found: ./data/config/config.yaml

### ISSUE THREAD

**Issue by Chr1s-T** [moeakwak/chatgpt-web-share#238]
直接运行main.py报错api.exceptions.ConfigException: ConfigException: [-1] errors.config Config file not found: ./data/config/config.yaml，怎么解决？

**Comment by tchivs** [comment]
把这个配置放到./data/config/config.yaml里面

```yaml
openai_web:
  is_plus_account: false
  chatgpt_base_url: http://go-chatgpt-api:8080/chatgpt/backend-api/
  proxy:
  common_timeout: 10
  ask_timeout: 600
openai_api:
  openai_base_url: https://api.openai.com/v1/
  proxy:
  connect_timeout: 10
  read_timeout: 20
common:
  print_sql: false
  create_initial_admin_user: true
  initial_admin_user_username: admin
  initial_admin_user_password: password
  sync_conversations_on_startup: true
  sync_conversations_regularly: false
http:
  host: 127.0.0.1
  port: 8000
  cors_allow_origins:
  - http://localhost
  - http://127.0.0.1
data:
  data_dir: ./data
  database_url: sqlite+aiosqlite:///data/database.db
  mongodb_url: mongodb://cws:password@mongo:27017
  run_migration: false
auth:
  jwt_secret: MODIFY_THIS_TO_RANDOM_SECRET
  jwt_lifetime_seconds: 86400
  cookie_max_age: 86400
  cookie_name: user_auth
  user_secret: MODIFY_THIS_TO_RANDOM_SECRET
stats:
  ask_stats_ttl: 7776000
  request_stats_ttl: 2592000
  request_stats_filter_keywords:
  - /status
log:
  console_log_level: INFO

```
