### ISSUE TITLE
2023年7月20日开始的报错 连接被服务终止

### ISSUE THREAD

**Issue by jasonwagz** [moeakwak/chatgpt-web-share#240]
<img width="654" alt="微信截图_20230720114254" src="https://github.com/moeakwak/chatgpt-web-share/assets/27673277/72fed847-3c38-4822-8bae-2cdfd0528fb4">

**Comment by nianzecong** [comment]
+1

版本：v0.3.15
错误日志如下：
2023/07/20 11:42:38.727     INFO: [uvicorn.error]	connection open
2023/07/20 11:42:38.733    DEBUG: [cws.api.routers.chat]	xxx connected to websocket
2023/07/20 11:42:39.479  WARNING: [cws.api.routers.chat]	Field missing. Details: {'conversation_id': '649c8074-xxxx-xxxx-xxxx-ece72e9d3e32', 'message_id': '91220b03-xxxx-xxxx-xxxx-aef5b761a609', 'is_completion': False, 'moderation_response': {'flagged': False, 'blocked': False, 'moderation_id': 'modr-7eEqlK0TOxxxxxxxxxxQ39U'}}
2023/07/20 11:42:39.479    DEBUG: [cws.api.routers.chat]	terminated ask 649c8074-xxxx-xxxx-xxxx-ece72e9d3e32 (ChatModels.default) because of error
2023/07/20 11:42:39.515     INFO: [uvicorn.error]	connection closed

**Comment by yanwen** [comment]
0.4.4 也一样有报错,但可以用。

> +1
> 
> 版本：v0.3.15 错误日志如下： 2023/07/20 11:42:38.727 INFO: [uvicorn.error] connection open 2023/07/20 11:42:38.733 DEBUG: [cws.api.routers.chat] xxx connected to websocket 2023/07/20 11:42:39.479 WARNING: [cws.api.routers.chat] Field missing. Details: {'conversation_id': '649c8074-xxxx-xxxx-xxxx-ece72e9d3e32', 'message_id': '91220b03-xxxx-xxxx-xxxx-aef5b761a609', 'is_completion': False, 'moderation_response': {'flagged': False, 'blocked': False, 'moderation_id': 'modr-7eEqlK0TOxxxxxxxxxxQ39U'}} 2023/07/20 11:42:39.479 DEBUG: [cws.api.routers.chat] terminated ask 649c8074-xxxx-xxxx-xxxx-ece72e9d3e32 (ChatModels.default) because of error 2023/07/20 11:42:39.515 INFO: [uvicorn.error] connection closed

**Comment by purezhang** [comment]
ver 0.3.15
刷新后可以获取 直接在openai 页面的问题及回答信息。

日志中报错：
2023/07/20 12:36:40.982     INFO: [uvicorn.error]       ('172.23.0.1', 0) - "WebSocket /conv" [accepted]
2023/07/20 12:36:40.985     INFO: [uvicorn.error]       connection open
2023/07/20 12:36:40.990    DEBUG: [cws.api.routers.chat]        yu connected to websocket
2023/07/20 12:36:41.889  WARNING: [cws.api.routers.chat]        Field missing. Details: {'conversation_id': 'e9076a3d-2e1a-4b17-b259-8c8308d4971a', 'message_id': '8d8c559a-f2df-4347-8d4e-2012a4e95aa0', 'is_completion': False, 'moderation_response': {'flagged': False, 'blocked': False, 'moderation_id': 'modr-7eFh3lvW68NIjrn2rQHbG7hVBtet4'}}
2023/07/20 12:36:41.889    DEBUG: [cws.api.routers.chat]        terminated ask e9076a3d-2e1a-4b17-b259-8c8308d4971a (ChatModels.default) because of error
2023/07/20 12:36:42.154     INFO: [uvicorn.error]       connection closed
2023/07/20 12:36:42.426     INFO: [cws.access]  172.23.0.1:0 | GET /user/me HTTP/1.1 | 200 OK | 9 ms

**Comment by RogerPu** [comment]
相同的报错

**Comment by dwdcth** [comment]
相同的报错 +1

**Comment by shijilin0116** [comment]
相同报错+1，有时候能拿到回复中的前几个字，报错同样为[1001]连接被服务端终止

**Comment by r1172464137** [comment]
同问题

**Comment by nianzecong** [comment]
试了一下新版本的 0.4.0-alpha4.4可以用，但是遇到几个问题：
1、不兼容之前的配置，账号需要重新建，参考https://github.com/moeakwak/chatgpt-web-share/issues/187 
2、好像不兼容旧的会话，分配旧会话给用户之后继续对话会报错
~~3、不兼容safari~~
~~4、会话选GPT-4模型的时候实际上是GPT-3，但是GPT-4 Mobile模型是正确的~~
<img width="810" alt="image" src="https://github.com/moeakwak/chatgpt-web-share/assets/10190293/081e1ae4-3dee-465e-91d7-c3b9252b7f3f">
<img width="806" alt="image" src="https://github.com/moeakwak/chatgpt-web-share/assets/10190293/eb63cfcc-2eba-4c24-9734-a85ca44208c2">

**Comment by aldington-david** [comment]
怎么有的说4.4能用有的不行，说是sse响应变了，等修吧

**Comment by soyisou** [comment]
4.4版本，苹果手机和web浏览器都正常，但是安卓手机有适配问题，即安卓手机网页版对话记录网页被写死了，不能上下滚动对话记录

**Comment by wangchao112211** [comment]
我也是遇到相同的问题，请问大佬怎么解决呀

**Comment by wangchao112211** [comment]
错误信息：：2023/07/26 00:03:53.512    DEBUG: [cws.api.routers.chat]        xgx connected to websocket
2023/07/26 00:03:54.561  WARNING: [cws.api.routers.chat]        Field missing. Details: {'conversation_id': '06a1e931-d938-4d82-acb8-55c3eaed3444', 'message_id': 'daa84bd0-409c-4d59-b66c-a0605a675c9f', 'is_completion': False, 'moderation_response': {'flagged': False, 'blocked': False, 'moderation_id': 'modr-7gEnqNoGIRqaAHz6VEeCb6njNqPiT'}}
2023/07/26 00:03:54.562    DEBUG: [cws.api.routers.chat]        terminated ask 06a1e931-d938-4d82-acb8-55c3eaed3444 (ChatModels.default) because of error
2023/07/26 00:03:55.120     INFO: [uvicorn.error]       connection closed
2023/07/26 00:03:55.172     INFO: [cws.access]  ***********:0 | GET /user/me HTTP/1.1 | 200 OK | 11 ms
2023/07/26 00:04:44.891     INFO: [uvicorn.error]       ('*********', 0) - "WebSocket /conv" [accepted]
2023/07/26 00:04:44.897     INFO: [uvicorn.error]       connection open
2023/07/26 00:04:44.905    DEBUG: [cws.api.routers.chat]        xgx connected to websocket
2023/07/26 00:04:46.658  WARNING: [cws.api.routers.chat]        Field missing. Details: {'conversation_id': '58e91233-acf1-49bd-aaaf-de91febbff52', 'message_id': '5a4975d6-3e63-4604-b162-bce85f4ab485', 'is_completion': False, 'moderation_response': {'flagged': False, 'blocked': False, 'moderation_id': 'modr-7gEog4afCtcXqBoAWnfUxLO8iJ6Er'}}
2023/07/26 00:04:46.660    DEBUG: [cws.api.routers.chat]        terminated ask 58e91233-acf1-49bd-aaaf-de91febbff52 (ChatModels.default) because of error
2023/07/26 00:04:47.136     INFO: [uvicorn.error]       connection closed
2023/07/26 00:04:47.568     INFO: [cws.access]  ********:0 | GET /user/me HTTP/1.1 | 200 OK | 12 ms
2023/07/26 09:26:23.794     INFO: [cws.access]  ********:0 | GET /conv/1ce733b7-5f60-45f8-8b21-ca7128665b62 HTTP/1.1 | 200 OK | 700 ms
2023/07/26 09:26:45.096     INFO: [uvicorn.error]       ('**********', 0) - "WebSocket /conv" [accepted]
2023/07/26 09:26:45.101     INFO: [uvicorn.error]       connection open
2023/07/26 09:26:45.107    DEBUG: [cws.api.routers.chat]        admin connected to websocket
2023/07/26 09:26:48.248  WARNING: [cws.api.routers.chat]        Field missing. Details: {'conversation_id': 'fa2aa061-10a0-4abf-9ba4-95cd07bf0632', 'message_id': '0ec302d9-2d2c-4172-9987-14a18614e526', 'is_completion': False, 'moderation_response': {'flagged': False, 'blocked': False, 'moderation_id': 'modr-7gNaXoCsJhfZbV1kIgDxQwH7tv4N4'}}
2023/07/26 09:26:48.250    DEBUG: [cws.api.routers.chat]        terminated ask fa2aa061-10a0-4abf-9ba4-95cd07bf0632 (ChatModels.default) because of error
2023/07/26 09:26:48.490     INFO: [uvicorn.error]       connection closed
2023/07/26 09:26:48.976     INFO: [cws.access]  ********:0 | GET /user/me HTTP/1.1 | 200 OK | 12 ms

**Comment by colin4k** [comment]
进入容器，例如：
```
docker exec -it chatgpt-web-share_chatgpt-share_1 /bin/sh
```
然后修改/usr/local/lib/python3.10/site-packages/revChatGPT/V1.py文件，搜索`raise ValueError(f"Field missing. Details: {str(line)}")`，将其替换为continue，有两处需要修改，如下：
```
if not self.__check_fields(line):
                    #raise ValueError(f"Field missing. Details: {str(line)}")
                    continue
```
修改完后重启容器即可
```
docker restart chatgpt-web-share_chatgpt-share_1
```

**Comment by funny-cat-happy** [comment]
由于sse接口调整，所以api会出现调用错误，稳定版的镜像v0.3.15因为revchatgpt调整导致无法在alpine镜像中打包成功，故只能使用测试版，下面是我个人打包的镜像，仅供暂时过渡使用
目录的创建方式按照 https://github.com/moeakwak/chatgpt-web-share/issues/187 来进行
docker-compose.yaml:
```
version: "3"
services:
  chatgpt-web-share:
    image: funnycathappy/chatgpt-web-share:4.0
    container_name: cws
    restart: always
    ports:
      - 80:80  #端口可调整
    volumes:
      - ./data:/app/backend/data
    environment:
      - TZ=Asia/Shanghai
      - CWS_CONFIG_DIR=/app/backend/data/config
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/backend-api/
    depends_on:
      - mongo
      - go-chatgpt-api

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: cws
      MONGO_INITDB_ROOT_USERNAME: cws
      MONGO_INITDB_ROOT_PASSWORD: password


  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api:latest
    environment:
      - GIN_MODE=release
    restart: unless-stopped
```
config.yaml:
```
openai_web:
  enabled: true
  is_plus_account: false
  chatgpt_base_url: http://go-chatgpt-api:8080/chatgpt/backend-api/
  proxy:
  common_timeout: 10
  ask_timeout: 600
  enabled_models:
  - gpt_3_5
  - gpt_4
  - gpt_4_browsing
  - gpt_4_plugins
  model_code_mapping:
    gpt_3_5: text-davinci-002-render-sha
    gpt_3_5_mobile: text-davinci-002-render-sha-mobile
    gpt_4: gpt-4
    gpt_4_mobile: gpt-4-mobile
    gpt_4_browsing: gpt-4-browsing
    gpt_4_plugins: gpt-4-plugins
openai_api:
  enabled: true
  openai_base_url: https://api.openai.com/v1/
  proxy:
  connect_timeout: 10
  read_timeout: 20
  enabled_models:
  - gpt_3_5
  - gpt_4
  model_code_mapping:
    gpt_3_5: gpt-3.5-turbo
    gpt_4: gpt-4
common:
  sync_conversations_on_startup: true
  sync_conversations_regularly: false
  print_sql: false
  create_initial_admin_user: true
  initial_admin_user_username: admin
  initial_admin_user_password: password
http:
  host: 127.0.0.1
  port: 8000
  cors_allow_origins:
  - http://localhost
  - http://127.0.0.1
data:
  data_dir: ./data
  database_url: sqlite+aiosqlite:///data/database.sqlite
  mongodb_url: mongodb://cws:password@mongo:27017
  run_migration: false
auth:
  jwt_secret: MODIFY_THIS_TO_RANDOM_SECRET
  jwt_lifetime_seconds: 86400
  cookie_max_age: 86400
  cookie_name: user_auth
  user_secret: MODIFY_THIS_TO_RANDOM_SECRET
stats:
  ask_stats_ttl: 7776000
  request_stats_ttl: 2592000
  request_stats_filter_keywords:
  - /status
log:
  console_log_level: INFO
```
credentials.yaml:
```
openai_web_access_token: "***"
openai_api_key: "***"
```
