### ISSUE TITLE
会话中自己发送的内容不显示

### ISSUE THREAD

**Issue by Mouriya-Emma** [moeakwak/chatgpt-web-share#274]
**Version**
v0.4.0-alpha7.4

**What's your deploying environment?**
- [x] Docker
- [ ] Caddy
- [x] Other

**Describe the problem**
对话时自己发送的内容在当时不显示，刷新页面后正常，这是一个feature吗

![0DC6F5EAB3D6628E9A127CA9F3D3A65D](https://github.com/moeakwak/chatgpt-web-share/assets/85676458/54882871-3d23-4cda-a27b-46ca06d93c23)

**Your config.yaml or other configurations**

```yml
openai_web:
  is_plus_account: true
  chatgpt_base_url: http://gapi:8080/chatgpt/backend-api/
  proxy:
  common_timeout: 10
  ask_timeout: 600
openai_api:
  enabled: false
  openai_base_url: https://api.openai.com/v1/
  proxy:
  connect_timeout: 10
  read_timeout: 20
common:
  print_sql: false
  create_initial_admin_user: true
  initial_admin_user_username: admin
  initial_admin_user_password: 1
  sync_conversations_on_startup: true
  sync_conversations_regularly: false
http:
  host: 127.0.0.1
  port: 8000
  cors_allow_origins:
  - http://localhost
  - http://127.0.0.1
data:
  data_dir: ./data
  database_url: sqlite+aiosqlite:///data/database.db
  mongodb_url: mongodb://cws:2@mongo:27017
  run_migration: false
auth:
  jwt_secret: MODIFY_THIS_TO_RANDOM_SECRET
  jwt_lifetime_seconds: 86400
  cookie_max_age: 86400
  cookie_name: user_auth
  user_secret: MODIFY_THIS_TO_RANDOM_SECRET
stats:
  ask_stats_ttl: 7776000
  request_stats_ttl: 2592000
  request_stats_filter_keywords:
  - /status
log:
  console_log_level: INFO
```
