### ISSUE TITLE
plus 用户无法使用 gpt-4 ( DEBUG: [cws.api.routers.chat] terminated ask None (gpt_4_browsing) because of error )

### ISSUE THREAD

**Issue by hexonal** [moeakwak/chatgpt-web-share#281]
- 问题: 当我的账号为 plus 用户且填入后报错了
- 报错如下:
日志报错: 
```log
chatgpt-web-share  | 2023/11/08 22:45:26.915    DEBUG: [cws.api.routers.chat] terminated ask None (gpt_4_browsing) because of error
go-chatgpt-api  | WARN[0092] a valid HAR file required         
go-chatgpt-api  | WARN[0344] a valid HAR file required         
go-chatgpt-api  | [GIN] 2023/11/08 - 22:45:26 | 403 |     901.281µs |   192.168.208.4 | POST     "/chatgpt/backend-api/conversation"
go-chatgpt-api  | [GIN] 2023/11/08 - 22:48:01 | 403 |     216.285µs |   192.168.208.4 | POST     "/chatgpt/backend-api/conversation"
go-chatgpt-api  | WARN[0499] a valid HAR file required     

```

- version: 0.4.0-alpha7.5
- docker-compose.yml
```yaml
version: "3.8"

services:
  chatgpt-web-share:
    image: ghcr.io/moeakwak/chatgpt-web-share:0.4.0-alpha7.5
    container_name: chatgpt-web-share
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./data:/app/backend/data
    environment:
      - TZ=Asia/Shanghai
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/backend-api/
      - CWS_CONFIG_DIR=/app/backend/data/config

    depends_on:
      - go-chatgpt-api

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: cws
      MONGO_INITDB_ROOT_USERNAME: cws
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db:/data/db
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api:latest
    # ports:
      # - 8080:8080 # 如果你需要暴露端口如一带多，可以取消注释
    environment:
      - GIN_MODE=release
    restart: unless-stopped
```
- config.yaml
```yaml
openai_web:
  enabled: true
  is_plus_account: true
  chatgpt_base_url: http://go-chatgpt-api:8080/chatgpt/backend-api/
  proxy:
  common_timeout: 20
  ask_timeout: 600
  sync_conversations_on_startup: true
  sync_conversations_schedule: true
  sync_conversations_schedule_interval_hours: 12
  enabled_models:
  - gpt_3_5
  - gpt_4
  - gpt_4_code_interpreter
  - gpt_4_plugins
  - gpt_4_browsing
  - gpt_4_dalle
  - gpt_3_5_mobile
  - gpt_4_mobile
  model_code_mapping:
    gpt_3_5: text-davinci-002-render-sha
    gpt_3_5_mobile: text-davinci-002-render-sha-mobile
    gpt_4: gpt-4
    gpt_4_mobile: gpt-4-mobile
    gpt_4_browsing: gpt-4-browsing
    gpt_4_plugins: gpt-4-plugins
    gpt_4_code_interpreter: gpt-4-code-interpreter
    gpt_4_dalle: gpt-4-dalle
  file_upload_strategy: browser_upload_when_file_size_exceed
  enable_uploading_attachments: true
  enable_uploading_multimodal_images: true
openai_api:
  enabled: false
  openai_base_url: https://api.openai.com/v1/
  proxy:
  connect_timeout: 10
  read_timeout: 20
  enabled_models:
  - gpt_3_5
  - gpt_4
  model_code_mapping:
    gpt_3_5: gpt-3.5-turbo
    gpt_4: gpt-4
common:
  print_sql: true
  create_initial_admin_user: true
  initial_admin_user_username: zhangsan
  initial_admin_user_password: zhangsan
http:
  host: 127.0.0.1
  port: 8000
  cors_allow_origins:
  - http://localhost:8000
  - http://localhost:5173
  - http://127.0.0.1:8000
  - http://127.0.0.1:5173
data:
  data_dir: ./data
  database_url: sqlite+aiosqlite:///data/database.db
  mongodb_url: mongodb://cws:password@mongo:27017
  mongodb_db_name: cws
  run_migration: true
  max_file_upload_size: 104857600
auth:
  jwt_secret: pass
  jwt_lifetime_seconds: 259200
  cookie_max_age: 259200
  user_secret: pass
stats:
  ask_stats_ttl: 7776000
  request_stats_ttl: 2592000
  request_stats_filter_keywords:
  - /status
log:
  console_log_level: DEBUG
```
- credentials.yaml
```yaml
openai_web_access_token: 自己的 token,https://chat.openai.com/api/auth/session的accessToken 
  
openai_api_key: 没有设置

```
