### ISSUE TITLE
按照文档配置后，3.5 可以使用，4.0 报错

### ISSUE THREAD

**Issue by yongman** [moeakwak/chatgpt-web-share#300]
**Version**
v0.4.1

**What's your deploying environment?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
A clear and concise description of your problem.

GPT 3.5 能正常工作，选择 GPT 4 报错，使用 web access token， 账号已经订阅 Plus，在官网能正常使用4.0。

<img width="441" alt="image" src="https://github.com/moeakwak/chatgpt-web-share/assets/3875656/1c8c5b05-8a84-46ee-8607-e72dec663cda">

```
2023/11/25 23:37:54.028     INFO: [uvicorn.error] ('172.22.0.1', 0) - "WebSocket /chat" [accepted]
2023/11/25 23:37:54.032     INFO: [uvicorn.error] connection open
2023/11/25 23:37:54.043     INFO: [cws.api.routers.chat] admin connected to websocket
2023/11/25 23:37:54.176    ERROR: [cws.api.routers.chat] OpenaiWebException: [500] errors.openaiWeb {"code":"500","msg":"No solver available or solver is invalid"}
2023/11/25 23:37:54.228     INFO: [uvicorn.error] connection closed
```

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

```
openai_web:
  enabled: true
  is_plus_account: true
  chatgpt_base_url: http://ninja:7999/backend-api/
  proxy:
  common_timeout: 60
  ask_timeout: 600
  sync_conversations_on_startup: false
  sync_conversations_schedule: false
  sync_conversations_schedule_interval_hours: 12
  enabled_models:
  - gpt_3_5
  - gpt_4
  - gpt_4_mobile
  - gpt_4_browsing
  - gpt_4_code_interpreter
  - gpt_4_dalle
  model_code_mapping:
    gpt_3_5: text-davinci-002-render-sha
    gpt_3_5_mobile: text-davinci-002-render-sha-mobile
    gpt_4: gpt-4
    gpt_4_mobile: gpt-4-mobile
    gpt_4_browsing: gpt-4-browsing
    gpt_4_plugins: gpt-4-plugins
    gpt_4_code_interpreter: gpt-4-code-interpreter
    gpt_4_dalle: gpt-4-dalle
  file_upload_strategy: browser_upload_only
  disable_uploading: false
openai_api:
  enabled: false
  openai_base_url: https://api.openai.com/v1/
  proxy:
  connect_timeout: 10
  read_timeout: 20
  enabled_models: []
  model_code_mapping:
    gpt_3_5: gpt-3.5-turbo
    gpt_4: gpt-4
common:
  print_sql: false
  create_initial_admin_user: true
  initial_admin_user_username: admin
  initial_admin_user_password: xxx
http:
  host: 127.0.0.1
  port: 8000
  cors_allow_origins:
  - http://localhost:8000
  - http://localhost:5173
  - http://127.0.0.1:8000
  - http://127.0.0.1:5173
data:
...
auth:
...
stats:
  ask_stats_ttl: 7776000
  request_stats_ttl: 2592000
  request_stats_filter_keywords:
  - /status
log:
  console_log_level: INFO
```

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**
