### ISSUE TITLE
这个 ninja 为何要禁止外网访问？

### ISSUE THREAD

**Issue by CHN-STUDENT** [moeakwak/chatgpt-web-share#329]
**Version**
v0.4.4

**What's your deploying environment?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
如题，一台国内VPS，部署魔法服务在宿主机；ninja 和 cws 使用 docker 部署，设置仅本机监听，使用 nginx 代理 cws，可正常使用。 
作者建议关闭 ninja 外网监听配置以提升安全。
想了一种方案，使用 nginx 反代 ninja 设置 http 密码登录，方便 har 上传，不过不知道有没有效果，请给点建议。

docker-compse.yaml

```
version: "3"

services:
  chatgpt-web-share:
    image: ghcr.io/chatpire/chatgpt-web-share:latest
    container_name: cws
    restart: unless-stopped
    ports:
#      - 5000:80
      - 127.0.0.1:5000:80
    volumes:
      - ./data:/app/backend/data
    environment:
      - TZ=${TZ}
      - CWS_CONFIG_DIR=/app/backend/data/config
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:6.0
    restart: always
    # ports:
    #   - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  ninja:
    image: ghcr.io/gngpp/ninja:latest
    container_name: ninja
    restart: unless-stopped
    command: run 
    ports:
#      - 7999:7999 
     - "127.0.0.1:7999:7999"
    environment:
      - TZ=Asia/Shanghai
      - PROXIES=all|http://172.24.0.1:1081 # 魔法服务部分，172.24.0.1 指的宿主机
    volumes:
      - "./har/gpt3:/root/.gpt3"
      - "./har/gpt4:/root/.gpt4"

```

vhost.conf
```
server {
  listen 80;
  listen [::]:80;
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  ssl_certificate /data/ssl/xxx.com.crt;
  ssl_certificate_key /data/ssl/xxx.com.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  ssl_ciphers TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256:EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
  ssl_prefer_server_ciphers on;
  ssl_session_timeout 10m;
  ssl_session_cache builtin:1000 shared:SSL:10m;
  ssl_buffer_size 1400;
  add_header Strict-Transport-Security max-age=15768000;
  ssl_stapling on;
  ssl_stapling_verify on;
  ssl_stapling_file  /data/ssl/ocsp/xxx.com.ocsp.resp;
  server_name xxx.com;
  access_log /data/wwwlogs/nginx.log combined;
  if ($ssl_protocol = "") { return 301 https://$host$request_uri; }
  

  location / {
    proxy_buffering off;
    proxy_pass http://127.0.0.1:5000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade; 
    proxy_set_header HOST $host;
    proxy_set_header X-Real-Ip $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;

  }

}

```
