### ISSUE TITLE
Failed to retrieve the plugin list

### ISSUE THREAD

**Issue by Temtselt** [moeakwak/chatgpt-web-share#336]
**Version**
v0.4.5

**What's your deploying method?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
点击启用插件后显示启用插件成功，但是已启用插件列表显示“获取插件列表失败”。

**To Reproduce**
1. Go to 'OpenAI设置-OpenAI Web 插件设置-全部'
2. Click on '启用'
3. See Error '获取插件列表失败'

**Expected behavior**
显示已启用的插件。

**Your config.yaml or other configurations**
```
openai_web:
  enabled: true
  is_plus_account: true
  chatgpt_base_url: http://ninja:7999/backend-api/
  proxy:
  common_timeout: 20
  ask_timeout: 600
  sync_conversations_on_startup: true
  sync_conversations_schedule: true
  sync_conversations_schedule_interval_hours: 12
  enabled_models:
  - gpt_3_5
  - gpt_4
  - gpt_4_plugins
  - gpt_4_dalle
  - gpt_4_code_interpreter
  - gpt_4_browsing
  model_code_mapping:
    gpt_3_5: text-davinci-002-render-sha
    gpt_3_5_mobile: text-davinci-002-render-sha-mobile
    gpt_4: gpt-4
    gpt_4_mobile: gpt-4-mobile
    gpt_4_browsing: gpt-4-browsing
    gpt_4_plugins: gpt-4-plugins
    gpt_4_code_interpreter: gpt-4-code-interpreter
    gpt_4_dalle: gpt-4-dalle
  file_upload_strategy: browser_upload_only
  disable_uploading: false
openai_api:
  enabled: false
  openai_base_url: https://api.openai.com/v1/
  proxy:
  connect_timeout: 10
  read_timeout: 20
  enabled_models:
  - gpt_3_5
  - gpt_4
  model_code_mapping:
    gpt_3_5: gpt-3.5-turbo
    gpt_4: gpt-4
common:
  print_sql: false
  create_initial_admin_user: true
  initial_admin_user_username:
  initial_admin_user_password: 
http:
  host: 127.0.0.1
  port: 8000
  cors_allow_origins:
  - http://localhost:8000
  - http://localhost:5173
  - http://127.0.0.1:8000
  - http://127.0.0.1:5173
data:
  data_dir: ./data
  database_url: sqlite+aiosqlite:///data/database.db
  mongodb_url: 
  mongodb_db_name: cws
  run_migration: true
  max_file_upload_size: 104857600
auth:
  jwt_secret: eJLGKnLC834Sztce
  jwt_lifetime_seconds: 259200
  cookie_max_age: 259200
  user_secret: 
stats:
  ask_stats_ttl: 7776000
  request_stats_ttl: 2592000
  request_stats_filter_keywords:
  - /status
log:
  console_log_level: INFO
```

**Screenshots or running logs**
![image](https://github.com/chatpire/chatgpt-web-share/assets/45378272/5f40c49c-2c81-4869-a421-5c102d5f97bb)

![image](https://github.com/chatpire/chatgpt-web-share/assets/45378272/55156c55-a42f-4931-bf23-ae80d242b1e6)

**Additional context**
