### ISSUE TITLE
未知错误: Field missing. Details: {‘message’: None, ‘conversation_id’: ‘337525c0-549c-41dd-aa78-63893b0b53dc’, ‘error’: ‘Error in message stream’}}

### ISSUE THREAD

**Issue by tanpengsccd** [moeakwak/chatgpt-web-share#34]
**Version**
v0.2.17

**What's your deploying method?**
Docker +Nginx(宝塔)

**Describe the bug**
![image](https://user-images.githubusercontent.com/13959880/227230951-fef4a409-3ab9-481e-bea7-6ca5df3a55e1.png)

未知错误: Field missing. Details: {‘message’: None, ‘conversation_id’: ‘337525c0-549c-41dd-aa78-63893b0b53dc’, ‘error’: ‘Error in message stream’}}

**To Reproduce**
只要提这个问题就会出现
```
我要在公司内部做一次技术分享，主题是“多重身份(Multi-Identity) 和 多币种钱包(Multi-Wallet)”。
请帮我写一篇文章，题目就叫《多重身份的前身-多币种钱包》。
文章的长度暂定在 5000 字左右，语气可以轻松一些，对文章的结构没有特别的要求，但需要阐述清楚以下几个问题：

什么是 “多币种钱包”
“多币种钱包”的应用场景
市面上有哪些“多币种钱包”的产品
什么是 “多重身份”
“多重身份”的应用场景
市面上有哪些“多重身份”的产品
怎么由 “多币种钱包” 演进到 “多重身份” 的
注意：内容尽量由浅入深，应用场景部分举一些具体的例子，介绍相关产品时配一些图片。
```
已经出现2次.
该会话也会丢失.

**Expected behavior**
正常显示
**Your config.yaml or other configurations**
```yaml
print_sql: false
host: "127.0.0.1"
port: 8000
database_url: "sqlite+aiosqlite:////data/database.db"
run_migration: false

jwt_secret: "123."    # 用于生成 jwt token，需要自行设置
jwt_lifetime_seconds: 86400
cookie_max_age: 86400           # 登录过期时间
user_secret: "123."  # 用于生成用户密码，需要自行设置

sync_conversations_on_startup: true # 是否在启动时同步同步 ChatGPT 对话，建议启用
create_initial_admin_user: false     # 是否创建初始管理员用户
create_initial_user: false          # 是否创建初始普通用户
initial_admin_username: "admin"       # 初始管理员用户名
initial_admin_password: "123"    # 初始管理员密码
# initial_user_username: user         # 初始普通用户名
# initial_user_password: Shared123.     # 初始普通密码
# https://chat.openai.com/api/auth/session  
chatgpt_access_token: "XXX"    # 需要从 ChatGPT 获取
chatgpt_paid: true  # 是否为 ChatGPT Plus 用户
```
**Screenshots or running logs**
![image](https://user-images.githubusercontent.com/13959880/227231564-a110dde9-c3af-475e-86b6-56e7ceeb5c78.png)
2023/03/23 14:04:53.618    ERROR: [cws.api.routers.chat] Field missing. Details: {'message': None, 'conversation_id': '91766fb7-1449-4361-b373-0c66a68f3885', 'error': 'Error in message stream'}
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/13959880/227232203-074372d8-24c0-4211-b0dd-94026a322033.png">

**Additional context**
